name: Validation Automatique

on: [push] 

jobs:
  verification:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v3

      - name: Etape 1 - Compilation (Build)
      
        run: gcc tester.c -o mon_programme

      - name: Etape 2 - Execution des Tests
       
        run: ./mon_programme
